In [3]:
import pandas as pd
import numpy as np
import math
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
import gc

data = pd.read_csv('Previous/Previous_data/included_cohort_prep.csv')

In [4]:
data = pd.read_csv('/mnt/dicoms/borja_files/CovidVax_DM/data/currentData11072025/included_cohort.csv.gz')

/tmp/ipykernel_3504760/2344732822.py:1: DtypeWarning: Columns (11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/mnt/dicoms/borja_files/CovidVax_DM/data/currentData11072025/included_cohort.csv.gz')

In [3]:
len(data)

7371644

In [4]:
data.shape

(7371644, 84)

In [5]:
data.columns

Index(['NIA', 'sexe', 'data_naixement', 'abs_c', 'abs', 'pais_c',
       'N_vaccine_total', 'VACUNA_1_DATA', 'VACUNA_1_MOTIU', 'VACUNA_2_DATA',
       'VACUNA_2_MOTIU', 'VACUNA_3_DATA', 'VACUNA_3_MOTIU', 'VACUNA_1_DATA_pp',
       'VACUNA_2_DATA_pp', 'VACUNA_3_DATA_pp', 'DATA_DM_min', 'DM',
       'covid_bef_vax', 'test_date', 'test_res', 'test_date_covid_2',
       'test_res_covid_2', 'test_date_covid_3', 'test_res_covid_3',
       'test_date_imc_1', 'test_res_imc_1', 'test_date_imc_2',
       'test_res_imc_2', 'test_date_imc_3', 'test_res_imc_3', 'test_date_sp_1',
       'test_res_sp_1', 'test_date_sp_2', 'test_res_sp_2', 'test_date_sp_3',
       'test_res_sp_3', 'test_date_dp_1', 'test_res_dp_1', 'test_date_dp_2',
       'test_res_dp_2', 'test_date_dp_3', 'test_res_dp_3', 'test_date_abdo_1',
       'test_res_abdo_1', 'test_date_abdo_2', 'test_res_abdo_2',
       'test_date_abdo_3', 'test_res_abdo_3', 'test_date_bg_1',
       'test_res_bg_1', 'test_date_bg_2', 'test_res_bg_2', 'test_date_bg_3',
       'test_res_bg_3', 'test_date_chol_1', 'test_res_chol_1',
       'test_date_chol_2', 'test_res_chol_2', 'test_date_chol_3',
       'test_res_chol_3', 'test_date_smoking_1', 'test_res_smoking_1',
       'test_date_smoking_2', 'test_res_smoking_2', 'test_date_smoking_3',
       'test_res_smoking_3', 'test_date_gma_1', 'test_res_gma_1',
       'test_date_gma_2', 'test_res_gma_2', 'test_date_gma_3',
       'test_res_gma_3', 'test_date_socio_stat_1', 'test_res_socio_stat_1',
       'test_date_socio_stat_2', 'test_res_socio_stat_2',
       'test_date_socio_stat_3', 'test_res_socio_stat_3', 'age_1', 'age_2',
       'age_3', 'idabs', 'ISC reescalat'],
      dtype='object')

In [6]:
data[data.data_naixement>='2021-01-01']

Empty DataFrame
Columns: [NIA, sexe, data_naixement, abs_c, abs, pais_c, N_vaccine_total, VACUNA_1_DATA, VACUNA_1_MOTIU, VACUNA_2_DATA, VACUNA_2_MOTIU, VACUNA_3_DATA, VACUNA_3_MOTIU, VACUNA_1_DATA_pp, VACUNA_2_DATA_pp, VACUNA_3_DATA_pp, DATA_DM_min, DM, covid_bef_vax, test_date, test_res, test_date_covid_2, test_res_covid_2, test_date_covid_3, test_res_covid_3, test_date_imc_1, test_res_imc_1, test_date_imc_2, test_res_imc_2, test_date_imc_3, test_res_imc_3, test_date_sp_1, test_res_sp_1, test_date_sp_2, test_res_sp_2, test_date_sp_3, test_res_sp_3, test_date_dp_1, test_res_dp_1, test_date_dp_2, test_res_dp_2, test_date_dp_3, test_res_dp_3, test_date_abdo_1, test_res_abdo_1, test_date_abdo_2, test_res_abdo_2, test_date_abdo_3, test_res_abdo_3, test_date_bg_1, test_res_bg_1, test_date_bg_2, test_res_bg_2, test_date_bg_3, test_res_bg_3, test_date_chol_1, test_res_chol_1, test_date_chol_2, test_res_chol_2, test_date_chol_3, test_res_chol_3, test_date_smoking_1, test_res_smoking_1, test_date_smoking_2, test_res_smoking_2, test_date_smoking_3, test_res_smoking_3, test_date_gma_1, test_res_gma_1, test_date_gma_2, test_res_gma_2, test_date_gma_3, test_res_gma_3, test_date_socio_stat_1, test_res_socio_stat_1, test_date_socio_stat_2, test_res_socio_stat_2, test_date_socio_stat_3, test_res_socio_stat_3, age_1, age_2, age_3, idabs, ISC reescalat]
Index: []

[0 rows x 84 columns]

In [7]:
data[data.age_3<0]

Empty DataFrame
Columns: [NIA, sexe, data_naixement, abs_c, abs, pais_c, N_vaccine_total, VACUNA_1_DATA, VACUNA_1_MOTIU, VACUNA_2_DATA, VACUNA_2_MOTIU, VACUNA_3_DATA, VACUNA_3_MOTIU, VACUNA_1_DATA_pp, VACUNA_2_DATA_pp, VACUNA_3_DATA_pp, DATA_DM_min, DM, covid_bef_vax, test_date, test_res, test_date_covid_2, test_res_covid_2, test_date_covid_3, test_res_covid_3, test_date_imc_1, test_res_imc_1, test_date_imc_2, test_res_imc_2, test_date_imc_3, test_res_imc_3, test_date_sp_1, test_res_sp_1, test_date_sp_2, test_res_sp_2, test_date_sp_3, test_res_sp_3, test_date_dp_1, test_res_dp_1, test_date_dp_2, test_res_dp_2, test_date_dp_3, test_res_dp_3, test_date_abdo_1, test_res_abdo_1, test_date_abdo_2, test_res_abdo_2, test_date_abdo_3, test_res_abdo_3, test_date_bg_1, test_res_bg_1, test_date_bg_2, test_res_bg_2, test_date_bg_3, test_res_bg_3, test_date_chol_1, test_res_chol_1, test_date_chol_2, test_res_chol_2, test_date_chol_3, test_res_chol_3, test_date_smoking_1, test_res_smoking_1, test_date_smoking_2, test_res_smoking_2, test_date_smoking_3, test_res_smoking_3, test_date_gma_1, test_res_gma_1, test_date_gma_2, test_res_gma_2, test_date_gma_3, test_res_gma_3, test_date_socio_stat_1, test_res_socio_stat_1, test_date_socio_stat_2, test_res_socio_stat_2, test_date_socio_stat_3, test_res_socio_stat_3, age_1, age_2, age_3, idabs, ISC reescalat]
Index: []

[0 rows x 84 columns]

In [8]:
data[data.age_3<data.age_1]

Empty DataFrame
Columns: [NIA, sexe, data_naixement, abs_c, abs, pais_c, N_vaccine_total, VACUNA_1_DATA, VACUNA_1_MOTIU, VACUNA_2_DATA, VACUNA_2_MOTIU, VACUNA_3_DATA, VACUNA_3_MOTIU, VACUNA_1_DATA_pp, VACUNA_2_DATA_pp, VACUNA_3_DATA_pp, DATA_DM_min, DM, covid_bef_vax, test_date, test_res, test_date_covid_2, test_res_covid_2, test_date_covid_3, test_res_covid_3, test_date_imc_1, test_res_imc_1, test_date_imc_2, test_res_imc_2, test_date_imc_3, test_res_imc_3, test_date_sp_1, test_res_sp_1, test_date_sp_2, test_res_sp_2, test_date_sp_3, test_res_sp_3, test_date_dp_1, test_res_dp_1, test_date_dp_2, test_res_dp_2, test_date_dp_3, test_res_dp_3, test_date_abdo_1, test_res_abdo_1, test_date_abdo_2, test_res_abdo_2, test_date_abdo_3, test_res_abdo_3, test_date_bg_1, test_res_bg_1, test_date_bg_2, test_res_bg_2, test_date_bg_3, test_res_bg_3, test_date_chol_1, test_res_chol_1, test_date_chol_2, test_res_chol_2, test_date_chol_3, test_res_chol_3, test_date_smoking_1, test_res_smoking_1, test_date_smoking_2, test_res_smoking_2, test_date_smoking_3, test_res_smoking_3, test_date_gma_1, test_res_gma_1, test_date_gma_2, test_res_gma_2, test_date_gma_3, test_res_gma_3, test_date_socio_stat_1, test_res_socio_stat_1, test_date_socio_stat_2, test_res_socio_stat_2, test_date_socio_stat_3, test_res_socio_stat_3, age_1, age_2, age_3, idabs, ISC reescalat]
Index: []

[0 rows x 84 columns]

In [9]:
data[(data.VACUNA_1_DATA>data.VACUNA_2_DATA)]

Empty DataFrame
Columns: [NIA, sexe, data_naixement, abs_c, abs, pais_c, N_vaccine_total, VACUNA_1_DATA, VACUNA_1_MOTIU, VACUNA_2_DATA, VACUNA_2_MOTIU, VACUNA_3_DATA, VACUNA_3_MOTIU, VACUNA_1_DATA_pp, VACUNA_2_DATA_pp, VACUNA_3_DATA_pp, DATA_DM_min, DM, covid_bef_vax, test_date, test_res, test_date_covid_2, test_res_covid_2, test_date_covid_3, test_res_covid_3, test_date_imc_1, test_res_imc_1, test_date_imc_2, test_res_imc_2, test_date_imc_3, test_res_imc_3, test_date_sp_1, test_res_sp_1, test_date_sp_2, test_res_sp_2, test_date_sp_3, test_res_sp_3, test_date_dp_1, test_res_dp_1, test_date_dp_2, test_res_dp_2, test_date_dp_3, test_res_dp_3, test_date_abdo_1, test_res_abdo_1, test_date_abdo_2, test_res_abdo_2, test_date_abdo_3, test_res_abdo_3, test_date_bg_1, test_res_bg_1, test_date_bg_2, test_res_bg_2, test_date_bg_3, test_res_bg_3, test_date_chol_1, test_res_chol_1, test_date_chol_2, test_res_chol_2, test_date_chol_3, test_res_chol_3, test_date_smoking_1, test_res_smoking_1, test_date_smoking_2, test_res_smoking_2, test_date_smoking_3, test_res_smoking_3, test_date_gma_1, test_res_gma_1, test_date_gma_2, test_res_gma_2, test_date_gma_3, test_res_gma_3, test_date_socio_stat_1, test_res_socio_stat_1, test_date_socio_stat_2, test_res_socio_stat_2, test_date_socio_stat_3, test_res_socio_stat_3, age_1, age_2, age_3, idabs, ISC reescalat]
Index: []

[0 rows x 84 columns]

In [21]:
data[data.DM==1]

,NIA,sexe,data_naixement,abs_c,abs,pais_c,N_vaccine_total,VACUNA_1_DATA,VACUNA_1_MOTIU,VACUNA_2_DATA,...,test_res_socio_stat_1,test_date_socio_stat_2,test_res_socio_stat_2,test_date_socio_stat_3,test_res_socio_stat_3,age_1,age_2,age_3,idabs,ISC reescalat
139,3054230,H,1953-09-17T00:00:00.000Z,23.0,Barcelona 2-C,724.0,3,2021-04-28T23:00:00.000Z,Grups d'edat,2021-07-10T23:00:00.000Z,...,2.0,2021-01-01T00:00:00.000Z,2.0,2021-01-01T00:00:00.000Z,2.0,67.660160,67.860160,68.290297,23.0,13.297067
194,3487466,H,1981-02-17T00:00:00.000Z,205.0,Sant Boi de Llobregat 4,724.0,3,2021-06-16T23:00:00.000Z,Patologia de risc,2021-07-14T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,40.356050,40.432763,40.693037,205.0,42.868200
222,5876073,D,1975-10-09T00:00:00.000Z,224.0,Santa Coloma de Gramenet 3,724.0,3,2021-06-07T23:00:00.000Z,Patologia de risc,2021-07-05T23:00:00.000Z,...,4.0,2021-01-01T00:00:00.000Z,4.0,2021-01-01T00:00:00.000Z,4.0,45.695776,45.772489,46.298516,224.0,60.084877
255,2627012,H,1970-01-23T00:00:00.000Z,248.0,Terrassa B,724.0,3,2021-05-20T23:00:00.000Z,Grups d'edat,2021-06-10T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,51.358790,51.416324,51.994406,248.0,70.236305
282,1911784,H,1965-01-05T00:00:00.000Z,51.0,Barcelona 7-A,NaN,3,2021-06-10T23:00:00.000Z,Grups d'edat,2021-07-05T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,56.468379,56.536872,57.062900,51.0,29.798891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7371100,11322149,D,1959-01-14T00:00:00.000Z,109.0,Cornellà de Llobregat 2,724.0,2,2021-06-16T23:00:00.000Z,Grups d'edat,2022-07-20T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,62.465639,63.558790,63.640982,109.0,68.136792
7371155,9852819,H,1972-04-19T00:00:00.000Z,291.0,L'Hospitalet de Llobregat 4 Torrassa,724.0,2,2021-06-21T23:00:00.000Z,Grups d'edat,2022-11-22T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,49.208105,50.630023,50.712215,291.0,59.203790
7371238,83818747,D,1982-04-16T00:00:00.000Z,155.0,Mataró 4,586.0,1,2023-01-13T23:00:00.000Z,Grups d'edat,NaN,...,NaN,NaN,NaN,NaN,NaN,40.775228,40.857420,40.939612,155.0,40.828608
7371573,11174739,H,1976-10-07T00:00:00.000Z,361.0,El Masnou - Alella,356.0,2,2021-09-26T23:00:00.000Z,Grups d'edat,2022-12-11T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,45.002626,46.210845,46.293037,361.0,20.328464
7371596,83698177,D,1952-07-31T00:00:00.000Z,125.0,Girona 2,76.0,1,2023-02-15T23:00:00.000Z,Grups d'edat,NaN,...,NaN,NaN,NaN,NaN,NaN,70.594406,70.676598,70.758790,125.0,47.304757

In [23]:
data[data.DATA_DM_min>'01-01-2021']

,NIA,sexe,data_naixement,abs_c,abs,pais_c,N_vaccine_total,VACUNA_1_DATA,VACUNA_1_MOTIU,VACUNA_2_DATA,...,test_res_socio_stat_1,test_date_socio_stat_2,test_res_socio_stat_2,test_date_socio_stat_3,test_res_socio_stat_3,age_1,age_2,age_3,idabs,ISC reescalat
139,3054230,H,1953-09-17T00:00:00.000Z,23.0,Barcelona 2-C,724.0,3,2021-04-28T23:00:00.000Z,Grups d'edat,2021-07-10T23:00:00.000Z,...,2.0,2021-01-01T00:00:00.000Z,2.0,2021-01-01T00:00:00.000Z,2.0,67.660160,67.860160,68.290297,23.0,13.297067
194,3487466,H,1981-02-17T00:00:00.000Z,205.0,Sant Boi de Llobregat 4,724.0,3,2021-06-16T23:00:00.000Z,Patologia de risc,2021-07-14T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,40.356050,40.432763,40.693037,205.0,42.868200
222,5876073,D,1975-10-09T00:00:00.000Z,224.0,Santa Coloma de Gramenet 3,724.0,3,2021-06-07T23:00:00.000Z,Patologia de risc,2021-07-05T23:00:00.000Z,...,4.0,2021-01-01T00:00:00.000Z,4.0,2021-01-01T00:00:00.000Z,4.0,45.695776,45.772489,46.298516,224.0,60.084877
255,2627012,H,1970-01-23T00:00:00.000Z,248.0,Terrassa B,724.0,3,2021-05-20T23:00:00.000Z,Grups d'edat,2021-06-10T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,51.358790,51.416324,51.994406,248.0,70.236305
282,1911784,H,1965-01-05T00:00:00.000Z,51.0,Barcelona 7-A,NaN,3,2021-06-10T23:00:00.000Z,Grups d'edat,2021-07-05T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,56.468379,56.536872,57.062900,51.0,29.798891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7371100,11322149,D,1959-01-14T00:00:00.000Z,109.0,Cornellà de Llobregat 2,724.0,2,2021-06-16T23:00:00.000Z,Grups d'edat,2022-07-20T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,62.465639,63.558790,63.640982,109.0,68.136792
7371155,9852819,H,1972-04-19T00:00:00.000Z,291.0,L'Hospitalet de Llobregat 4 Torrassa,724.0,2,2021-06-21T23:00:00.000Z,Grups d'edat,2022-11-22T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,49.208105,50.630023,50.712215,291.0,59.203790
7371238,83818747,D,1982-04-16T00:00:00.000Z,155.0,Mataró 4,586.0,1,2023-01-13T23:00:00.000Z,Grups d'edat,NaN,...,NaN,NaN,NaN,NaN,NaN,40.775228,40.857420,40.939612,155.0,40.828608
7371573,11174739,H,1976-10-07T00:00:00.000Z,361.0,El Masnou - Alella,356.0,2,2021-09-26T23:00:00.000Z,Grups d'edat,2022-12-11T23:00:00.000Z,...,3.0,2021-01-01T00:00:00.000Z,3.0,2021-01-01T00:00:00.000Z,3.0,45.002626,46.210845,46.293037,361.0,20.328464
7371596,83698177,D,1952-07-31T00:00:00.000Z,125.0,Girona 2,76.0,1,2023-02-15T23:00:00.000Z,Grups d'edat,NaN,...,NaN,NaN,NaN,NaN,NaN,70.594406,70.676598,70.758790,125.0,47.304757

In [24]:
data[data.DATA_DM_min<'01-01-2021']

Empty DataFrame
Columns: [NIA, sexe, data_naixement, abs_c, abs, pais_c, N_vaccine_total, VACUNA_1_DATA, VACUNA_1_MOTIU, VACUNA_2_DATA, VACUNA_2_MOTIU, VACUNA_3_DATA, VACUNA_3_MOTIU, VACUNA_1_DATA_pp, VACUNA_2_DATA_pp, VACUNA_3_DATA_pp, DATA_DM_min, DM, covid_bef_vax, test_date, test_res, test_date_covid_2, test_res_covid_2, test_date_covid_3, test_res_covid_3, test_date_imc_1, test_res_imc_1, test_date_imc_2, test_res_imc_2, test_date_imc_3, test_res_imc_3, test_date_sp_1, test_res_sp_1, test_date_sp_2, test_res_sp_2, test_date_sp_3, test_res_sp_3, test_date_dp_1, test_res_dp_1, test_date_dp_2, test_res_dp_2, test_date_dp_3, test_res_dp_3, test_date_abdo_1, test_res_abdo_1, test_date_abdo_2, test_res_abdo_2, test_date_abdo_3, test_res_abdo_3, test_date_bg_1, test_res_bg_1, test_date_bg_2, test_res_bg_2, test_date_bg_3, test_res_bg_3, test_date_chol_1, test_res_chol_1, test_date_chol_2, test_res_chol_2, test_date_chol_3, test_res_chol_3, test_date_smoking_1, test_res_smoking_1, test_date_smoking_2, test_res_smoking_2, test_date_smoking_3, test_res_smoking_3, test_date_gma_1, test_res_gma_1, test_date_gma_2, test_res_gma_2, test_date_gma_3, test_res_gma_3, test_date_socio_stat_1, test_res_socio_stat_1, test_date_socio_stat_2, test_res_socio_stat_2, test_date_socio_stat_3, test_res_socio_stat_3, age_1, age_2, age_3, idabs, ISC reescalat]
Index: []

[0 rows x 84 columns]